import type { Room, Booking } from "./types";
import { addDays, subDays, set } from "date-fns";

export const rooms: Room[] = [
  {
    id: 1,
    name: "Vayu",
    capacity: 4,
    amenities: ["Whiteboard"],
    image: "https://picsum.photos/seed/vayu/600/400",
    maintenance: false,
    location: "Hyderabad",
  },
  {
    id: 2,
    name: "Prithvi",
    capacity: 8,
    amenities: ["Projector", "Video Conferencing"],
    image: "https://picsum.photos/seed/prithvi/600/400",
    maintenance: false,
    location: "Hyderabad",
  },
  {
    id: 3,
    name: "Jal",
    capacity: 12,
    amenities: ["Projector", "Whiteboard", "Video Conferencing"],
    image: "https://picsum.photos/seed/jal/600/400",
    maintenance: true,
    location: "Hyderabad",
  },
  {
    id: 4,
    name: "Akash",
    capacity: 6,
    amenities: ["Whiteboard", "Projector"],
    image: "https://picsum.photos/seed/akash/600/400",
    maintenance: false,
    location: "Hyderabad",
  },
  {
    id: 5,
    name: "Haleakala",
    capacity: 4,
    amenities: [],
    image: "https://picsum.photos/seed/haleakala/600/400",
    maintenance: false,
    location: "Hawaii",
  },
  {
    id: 6,
    name: "Pali",
    capacity: 20,
    amenities: ["Projector", "Whiteboard", "Video Conferencing", "Catering"],
    image: "https://picsum.photos/seed/pali/600/400",
    maintenance: false,
    location: "Hawaii",
  },
  {
    id: 7,
    name: "Napali Coast",
    capacity: 10,
    amenities: ["Projector", "Whiteboard"],
    image: "https://picsum.photos/seed/napali-coast/600/400",
    maintenance: false,
    location: "Hawaii",
  },
  {
    id: 8,
    name: "Hanalei",
    capacity: 16,
    amenities: ["Video Conferencing", "Catering"],
    image: "https://picsum.photos/seed/hanalei/600/400",
    maintenance: false,
    location: "Hawaii",
  },
  {
    id: 9,
    name: "Kilauea",
    capacity: 8,
    amenities: ["Projector", "Whiteboard"],
    image: "https://picsum.photos/seed/kilauea/600/400",
    maintenance: false,
    location: "Hawaii",
  },
];
