/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountOwnerCases: typeof import('./src/components/AccountOwner/AccountOwnerCases.vue')['default']
    AccountOwnerClients: typeof import('./src/components/AccountOwner/AccountOwnerClients.vue')['default']
    AccountOwnerDashboard: typeof import('./src/components/AccountOwner/AccountOwnerDashboard.vue')['default']
    App: typeof import('./src/App.vue')['default']
    ButtonLogin: typeof import('./src/components/GlobalComponents/Buttons/ButtonLogin.vue')['default']
    DefaultBgScreen: typeof import('./src/components/GlobalComponents/LoginScreens/DefaultBgScreen.vue')['default']
    ForgotPasswordCard: typeof import('./src/components/GlobalComponents/Cards/ForgotPasswordCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoginCard: typeof import('./src/components/GlobalComponents/Cards/LoginCard.vue')['default']
    LoginView: typeof import('./src/views/LoginView.vue')['default']
    MainLayout: typeof import('./src/components/GlobalComponents/MainLayout/MainLayout.vue')['default']
    MainLayoutView: typeof import('./src/views/MainLayoutView/MainLayoutView.vue')['default']
    NavHeader: typeof import('./src/components/Shared/NavHeader.vue')['default']
    NavSide: typeof import('./src/components/Shared/NavSide.vue')['default']
    OffCanvas: typeof import('./src/components/GlobalComponents/OffCanvas/OffCanvas.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleTest: typeof import('./src/views/SampleTest.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
