spring.datasource.url=jdbc:oracle:thin:@localhost:1521/REC_LOCAL
spring.datasource.username=innovan_user
spring.datasource.password=Innovan@123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

server.port=9022

security.jwt.secret-key=u8H2kL3P9vQxFz6JtR5sYwD1aZ9mVbH3nQ4eXcP7rh6jL8wS1yU2oT5pQ8rM0xV4
security.jwt.expiration-time=3600000

allowedOrigins=http://localhost:9002