worker_processes auto;
events { worker_connections 1024; }

http {
  server {
    listen 9022;

    # ---- FRONTEND (Next.js) ----
    location / {
      proxy_pass http://34.100.249.30:9002;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }

    # ---- BACKEND (Spring Boot API) ----
    location /api/ {
      rewrite ^/api(/.*)$ $1 break;
      proxy_pass http://34.100.249.30:9022;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }
}
